# Generated by Django 5.1.1 on 2024-09-05 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='title',
            new_name='name',
        ),
    ]
