# Generated by Django 5.1.1 on 2024-09-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_rename_title_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='img')),
            ],
        ),
    ]
