# Generated by Django 5.1.1 on 2024-09-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0003_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='subjecttype',
            old_name='name',
            new_name='title',
        ),
    ]
