# Generated by Django 5.1.1 on 2024-09-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0004_rename_name_subject_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='english_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
