# Generated by Django 5.1.1 on 2024-09-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0006_alter_course_end_date_alter_course_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Terminée', 'Terminée')], default='En cours', max_length=10),
        ),
    ]
