# Generated by Django 5.1.1 on 2024-09-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0008_remove_course_thumbnail_course_thumbnail_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='thumbnail_url',
            new_name='thumbnail',
        ),
    ]
