# Generated by Django 5.1.1 on 2024-09-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0009_rename_thumbnail_url_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='days',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
