# Generated by Django 5.1.1 on 2024-09-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0010_alter_course_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hour',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
