# Generated by Django 5.1.1 on 2024-09-14 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0011_course_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='frequency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
