# Generated by Django 5.1.1 on 2024-09-04 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='why_contact_us',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
